### ISSUE TITLE
TypeError: Path must be a string. Received null; at index.js:116:15

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/parse-git-config#4]
error output

```
% ❯ verb                                                                                               November 04, 06:02:12
[06:06:55] starting verb
[06:06:59] ✔ running tasks: [ 'readme' ]
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at Function.resolve (/home/charlike/.nvm/versions/node/v7.0.0/lib/node_modules/verb-generate-readme/node_modules/parse-git-config/index.js:116:15)
    at Function.parseSync [as sync] (/home/charlike/.nvm/versions/node/v7.0.0/lib/node_modules/verb-generate-readme/node_modules/parse-git-config/index.js:79:24)
    at Schema.module.exports (/home/charlike/.nvm/versions/node/v7.0.0/lib/node_modules/verb-generate-readme/node_modules/expand-pkg/lib/expanders/git.js:13:36)
    at Schema.normalizeField (/home/charlike/.nvm/versions/node/v7.0.0/lib/node_modules/verb-generate-readme/node_modules/map-schema/index.js:557:16)
    at Schema.update (/home/charlike/.nvm/versions/node/v7.0.0/lib/node_modules/verb-generate-readme/node_modules/map-schema/index.js:246:8)
    at Schema.module.exports (/home/charlike/.nvm/versions/node/v7.0.0/lib/node_modules/verb-generate-readme/node_modules/expand-pkg/lib/expanders/owner.js:14:10)
    at Schema.normalizeField (/home/charlike/.nvm/versions/node/v7.0.0/lib/node_modules/verb-generate-readme/node_modules/map-schema/index.js:557:16)
    at Schema.normalize (/home/charlike/.nvm/versions/node/v7.0.0/lib/node_modules/verb-generate-readme/node_modules/map-schema/index.js:497:27)
```

just found it, because just dont have `.git/` dir.

**Comment by doowb** [comment]
Try reinstalling `verbose/verb#dev` and `verb-generate-readme`.

[This issue on generate](https://github.com/generate/generate/issues/30#issuecomment-257387975) is probably referring to the same problem you're having. We updated the versions of the other modules to include the `parse-git-config` version that fixes this.

**Comment by tunnckoCore** [comment]
Oh yea, really. Forgot that. Probably will work.
